sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

collections:
  blog:
    output: true
  lab:
    output: true